version: "3.7"
services:
  plugin:
    build: .
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: "yarn test"
